### ISSUE TITLE
Error In Emacs 28.1

### ISSUE THREAD

**Issue by kstatz12** [razzmatazz/csharp-language-server#103]
```LSP :: csharp-ls: cannot compute refactorings for Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider: System.AggregateException: One or more errors occurred. (Service of type 'Microsoft.CodeAnalysis.Options.ILegacyGlobalOptionsWorkspaceService' is required to accomplish the task but is not available from the workspace.)
 ---> System.InvalidOperationException: Service of type 'Microsoft.CodeAnalysis.Options.ILegacyGlobalOptionsWorkspaceService' is required to accomplish the task but is not available from the workspace.
   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.CreateCodeActionWithDialogAsync(Document document, SyntaxNode typeDeclaration, INamedTypeSymbol containingType, ImmutableArray`1 members, CleanCodeGenerationOptionsProvider fallbackOptions, Boolean generateEquals, Boolean generateGetHashCode, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.CreateActionsAsync(Document document, SyntaxNode typeDeclaration, INamedTypeSymbol containingType, ImmutableArray`1 selectedMembers, CleanCodeGenerationOptionsProvider fallbackOptions, Boolean hasEquals, Boolean hasGetHashCode, Boolean withDialog, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.HandleNonSelectionAsync(CodeRefactoringContext context, CleanCodeGenerationOptionsProvider fallbackOptions)
   at Microsoft.CodeAnalysis.GenerateEqualsAndGetHashCodeFromMembers.GenerateEqualsAndGetHashCodeFromMembersCodeRefactoringProvider.ComputeRefactoringsAsync(CodeRefactoringContext context)
   --- End of inner exception stack trace ---
LSP :: csharp-ls: cannot compute refactorings for Microsoft.CodeAnalysis.CSharp.GenerateConstructorFromMembers.CSharpGenerateConstructorFromMembersCodeRefactoringProvider: System.AggregateException: One or more errors occurred. (Service of type 'Microsoft.CodeAnalysis.Options.ILegacyGlobalOptionsWorkspaceService' is required to accomplish the task but is not available from the workspace.)
 ---> System.InvalidOperationException: Service of type 'Microsoft.CodeAnalysis.Options.ILegacyGlobalOptionsWorkspaceService' is required to accomplish the task but is not available from the workspace.
   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.GenerateConstructorFromMembers.AbstractGenerateConstructorFromMembersCodeRefactoringProvider.HandleNonSelectionAsync(Document document, TextSpan textSpan, Nullable`1 desiredAccessibility, CleanCodeGenerationOptionsProvider fallbackOptions, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.GenerateConstructorFromMembers.AbstractGenerateConstructorFromMembersCodeRefactoringProvider.ComputeRefactoringsAsync(Document document, TextSpan textSpan, Action`2 registerSingleAction, Action`1 registerMultipleActions, Nullable`1 desiredAccessibility, CleanCodeGenerationOptionsProvider fallbackOptions, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---```

this happens when code completion triggers, i think. im not sure

**Comment by kstatz12** [comment]
Ive done some spelunking, so I know what is going on. TLDR Roslyn has a weird behavior. When the LSP tries to suggest refactorings on an empty line it calls `private async Task HandleNonSelectionAsync(
            CodeRefactoringContext context,
            CleanCodeGenerationOptionsProvider fallbackOptions)`

in this method it calls `var globalOptions = document.Project.Solution.Services.GetService<ILegacyGlobalOptionsWorkspaceService>();
            if (globalOptions == null)
                return;`

This is handled in `csharp-language-server` in the `WorkspaceInterceptor` where if the `GetService` call returns `null` which based on the signature for `GetService` in 
```
public abstract TLanguageService? GetService<TLanguageService>() where TLanguageService : ILanguageService;

        /// <summary>
        /// Gets a language specific service provided by the host identified by the service type. 
        /// If the host does not provide the service, this method returns throws <see cref="InvalidOperationException"/>.
        /// </summary>
        public TLanguageService GetRequiredService<TLanguageService>() where TLanguageService : ILanguageService
        {
            var service = GetService<TLanguageService>();
            if (service == null)
            {
                throw new InvalidOperationException(string.Format(WorkspacesResources.Service_of_type_0_is_required_to_accomplish_the_task_but_is_not_available_from_the_workspace, typeof(TLanguageService)));
            }

            return service;
        }
```

This signature implies that it returns a nullable reference of type `TLanguageService`. But the error we are getting is more in line with how `GetRequiredService` is implemented. I cant find the concrete implementation yet in roslyn (its a mess of inheritance)

but i think its a bug on there end
