### ISSUE TITLE
Error on neovim

### ISSUE THREAD

**Issue by Zeioth** [razzmatazz/csharp-language-server#106]
I've installed `csharp-language-server` using mason. 

But when I open a C# file I get the next errors

![screenshot_2023-08-12_17-31-51_219540441](https://github.com/razzmatazz/csharp-language-server/assets/3357792/c13ff9c2-26c2-47b0-9732-b2606da1261f)
![screenshot_2023-08-12_17-32-02_178694102](https://github.com/razzmatazz/csharp-language-server/assets/3357792/0c8657d4-c50b-4b14-ac9e-329c2616a1c4)
![screenshot_2023-08-12_17-32-08_554257612](https://github.com/razzmatazz/csharp-language-server/assets/3357792/198d93a3-5936-4cf9-90b3-dead3771cc25)

I've got dotnet and .NET 7.0.9 installed. I'm missing something?

**Comment by razzmatazz** [comment]
Hey @Zeioth 
Could you get the full log of the from neovim?
Last screenshot indicates some sort of a crash but heading lines are missing.
I am not an expert in neovim so I am not sure how to show errors from lsp integration exactly..

**Comment by Zeioth** [comment]
@razzmatazz I'm not sure where the error is being printed on. Using `:messages` don't display anything.

If I press `Enter` the error just keepts repeting
![screenshot_2023-08-12_18-03-41_338600694](https://github.com/razzmatazz/csharp-language-server/assets/3357792/3d82b811-bebd-433b-9dbc-1d1cf62a5120)

**Comment by Zeioth** [comment]
@razzmatazz I've been able to get the full log by using `:redir > ~/mylog.log` and then `:messages` after opening a C# file.

```
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.RoslynHelpers.findAndLoadSolutionOnDir@1019-6.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/RoslynHelpers.fs:line 1019
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, b result1, FSharpFunc`2 userCode) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 528
   at Ionide.LanguageServerProtocol.Server.sendServerNotification@111-3.Invoke(AsyncActivation`1 ctxt) in /_//src/LanguageServerProtocol.fs:line 111
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction) in D:\a\_work\1\s\src\FSharp.Core\async.fs:line 112
LSP[csharp_ls][Log] csharp-ls: serverEventLoop: crashed with System.Exception: no or .csproj/.fsproj or sln files found on /home/zeioth/.config/nvim
   at CSharpLanguageServer.State.loop@272-7.Invoke(Unit _arg4) in /home/runner/work/csharp-language-server/csharp-language-server/src/CSharpLanguageServer/State.fs:line 272
```

**Comment by Zeioth** [comment]
It seems to be saying it requires a .csproj file. I have another another project with a `.csproj`, when I open a file from the project, the next message shows instead:

```
LSP[csharp_ls][Info] csharp-ls: initializing, csharp-ls version 0.8.0.0; cwd: "/home/zeioth/.local/share/nvim/lazy/compiler.nvim/tests/examples/cs/build-dotnet"
LSP[csharp_ls][Info] csharp-ls: csharp-ls is released under MIT license and is not affiliated with Microsoft Corp.; see https://github.com/razzmatazz/csharp-language-server
LSP[csharp_ls][Info] csharp-ls: MSBuildLocator: will register ".NET Core SDK", Version=7.0.109 as default instance
LSP[csharp_ls][Log] csharp-ls: attempting to find and load solution based on cwd ("/home/zeioth/.local/share/nvim/lazy/compiler.nvim/tests/examples/cs/build-dotnet")..
LSP[csharp_ls][Log] csharp-ls: 0 solution(s) found: []
LSP[csharp_ls][Log] csharp-ls: no or multiple .sln files found on /home/zeioth/.local/share/nvim/lazy/compiler.nvim/tests/examples/cs/build-dotnet
LSP[csharp_ls][Log] csharp-ls: looking for .csproj/fsproj files on /home/zeioth/.local/share/nvim/lazy/compiler.nvim/tests/examples/cs/build-dotnet..
LSP[csharp_ls][Log] csharp-ls: loading project "/home/zeioth/.local/share/nvim/lazy/compiler.nvim/tests/examples/cs/build-dotnet/project.csproj"..
LSP[csharp_ls][Log] csharp-ls: OK, 1 project files loaded
```
