### ISSUE TITLE
Implement Interface CodeAction

### ISSUE THREAD

**Issue by EliSauder** [razzmatazz/csharp-language-server#90]
I don't know if implementing an interface's members is supposed to show up as a code action or not, however it isn't for me. 

If it is not supposed to show up, gotcha; but if it is, figured I should report it here.

<img width="669" alt="image" src="https://user-images.githubusercontent.com/24995216/234784756-c0198153-a84a-43f0-9a6d-9c1c09b343b1.png">

**Comment by razzmatazz** [comment]
do you get any errors on the console from lsp?i did notice that some other things broke after updating to a later roslyn release last time —Saulius MenkevičiusOn 2023-04-27, at 10:03, Elijah Sauder ***@***.***> wrote:﻿
I don't know if implementing an interface's members is supposed to show up as a code action or not, however it isn't for me.
If it is not supposed to show up, gotcha; but if it is, figured I should report it here.

**Comment by EliSauder** [comment]
I have not noticed any errors in the console. I also don't see any messages in LspLog regarding it.

**Comment by razzmatazz** [comment]
I just noticed some of the code actions broke when upgrading to a later version of roslyn:
```
[eglot] Server reports (type=4): csharp-ls: System.AggregateException: One or more errors occurred. (Service of type 'Microsoft.CodeAnalysis.GenerateType.IGenerateTypeOptionsService' is required to accomplish the task but is not available from the workspace.)
 ---> System.InvalidOperationException: Service of type 'Microsoft.CodeAnalysis.GenerateType.IGenerateTypeOptionsService' is required to accomplish the task but is not available from the workspace.
   at Microsoft.CodeAnalysis.Host.HostWorkspaceServices.GetRequiredService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.Host.SolutionServices.GetRequiredService[TWorkspaceService]()
   at Microsoft.CodeAnalysis.GenerateType.AbstractGenerateTypeService`6.GenerateTypeCodeActionWithOption.GetOptions(CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.CodeActions.CodeActionWithOptions.GetOperationsCoreAsync(IProgressTracker progressTracker, CancellationToken cancellationToken)
 ```

looking into it, most probably I will downgrade roslyn until I have a fix

**Comment by razzmatazz** [comment]
apparently an upgrade to 4.5.0 broke it, reverting to 4.4 (but no bugfix release)

**Comment by razzmatazz** [comment]
yeah, we need to introduce tests in csharp-ls, no way around it :(
